# Generated by Django 5.2 on 2025-04-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_seed_security_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='email',
            new_name='organization_email',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='full_name',
            new_name='organization_name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='phone_number',
            new_name='organization_phone',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='company_name',
        ),
    ]
