# Generated by Django 5.2 on 2025-04-14 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_email_organization_organization_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applicant',
            table='users_applicant',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='users_organization',
        ),
    ]
