# Generated by Django 5.2 on 2025-04-12 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_feedback_applicant_and_more'),
        ('users', '0004_remove_applicantprofile_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicantProfile',
        ),
        migrations.DeleteModel(
            name='OrganizationProfile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserSecurityAnswer',
        ),
    ]
