# Generated by Django 5.2 on 2025-04-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/jobs/'),
        ),
    ]
