# Generated by Django 5.2 on 2025-04-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_message_receiver_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
